//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timetable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplanes
    {
        public Airplanes()
        {
            this.Flights = new HashSet<Flights>();
        }
    
        public int AirplaneID { get; set; }
        public string AirplaneType { get; set; }
        public int NumberOfSeats { get; set; }
    
        public virtual ICollection<Flights> Flights { get; set; }
    }
}
