//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timetable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public System.Guid FlightID { get; set; }
        public int AirplaneID { get; set; }
        public string FlightNumber { get; set; }
        public int Origin { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public int Destination { get; set; }
        public System.DateTime ArrivalTime { get; set; }
    
        public virtual Airplanes Airplanes { get; set; }
        public virtual Airports Airports { get; set; }
        public virtual Airports Airports1 { get; set; }
    }
}
