USE [master]
GO

/****** Object:  Database [Weather]    Script Date: 19.03.2015 15:01:39 ******/
CREATE DATABASE [Weather]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Weather', FILENAME = N'H:\ProgramFiles\MSSQL12.IZOLDA2015\MSSQL\DATA\Weather.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Weather_log', FILENAME = N'H:\ProgramFiles\MSSQL12.IZOLDA2015\MSSQL\DATA\Weather_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Weather] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Weather].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Weather] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Weather] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Weather] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Weather] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Weather] SET ARITHABORT OFF 
GO

ALTER DATABASE [Weather] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Weather] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Weather] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Weather] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Weather] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Weather] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Weather] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Weather] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Weather] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Weather] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Weather] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Weather] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Weather] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Weather] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Weather] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Weather] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Weather] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Weather] SET RECOVERY FULL 
GO

ALTER DATABASE [Weather] SET  MULTI_USER 
GO

ALTER DATABASE [Weather] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Weather] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Weather] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Weather] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Weather] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Weather] SET  READ_WRITE 
GO


