//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string MiddleName { get; set; }
        public string PostName { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public string Token { get; set; }

        public static string GenerateRandomString(int length)
        {
            var str = new Char[length];
            Random rnd = new Random();
            for (int i = 0; i < length; i++)
            {
                if (rnd.Next(2) == 0)
                {
                    str[i] = Convert.ToChar(rnd.Next(26) + 'A');
                }
                else
                {
                    str[i] = Convert.ToChar(rnd.Next(26) + 'a');
                }

            }
            return new string(str);
        }
        public Dictionary<string, string> ToDictionary()
        {
            var dict = new Dictionary<string, string>();
            dict.Add("UserId", UserId.ToString());
            dict.Add("Login", Login);
            dict.Add("Password", Password);
            dict.Add("FirstName", FirstName);
            dict.Add("SecondName", SecondName);
            dict.Add("MiddleName", MiddleName);
            dict.Add("PostName", PostName);
            dict.Add("RoleId", RoleId.ToString());
            dict.Add("DateTo", DateTo.ToString());
            dict.Add("DateFrom", DateFrom.ToString());
            dict.Add("Token", Token);
            return dict;
        }
    }
}
